import json
import sys
sys.stdout.reconfigure(encoding='utf-8')

# Test 10 words NOT in golden standard using model knowledge
test_words = [
    "barrier",
    "basis",
    "be aware of",
    "be in charge of",
    "be made of",
    "be ready for",
    "bear",
    "beforehand",
    "behaviour",
    "benchmark"
]

# Generate records using model knowledge
records = []

# 1. barrier
records.append({
    "id": None,
    "english": "barrier",
    "type": "noun",
    "vietnamese": "rào cản; chướng ngại vật",
    "pronounce": "/ˈbæriə(r)/",
    "explain": "Một vật hoặc điều kiện ngăn cản sự chuyển động hoặc tiếp cận.",
    "example": "Language barriers can hinder effective communication in international business.",
    "example_vietnamese": "Rào cản ngôn ngữ có thể cản trở giao tiếp hiệu quả trong kinh doanh quốc tế.",
    "image_url": None,
    "audio_url": None,
    "difficulty": "medium",
    "cefr_level": "B2",
    "toeic_level": 600,
    "frequency": 45,
    "synonyms": ["obstacle", "hurdle", "obstruction", "impediment"],
    "antonyms": ["advantage", "assistance", "opportunity"],
    "word_family": [],
    "collocations": ["trade barrier", "barrier to entry", "break down barriers", "overcome barriers"],
    "phrasal_verbs": [],
    "grammar_pattern": "Common usage",
    "common_mistakes": None,
    "usage_note": "Thường dùng trong ngữ cảnh thương mại quốc tế và kinh doanh.",
    "topic": "General Business Operations",
    "mnemonic": None,
    "mnemonic_type": None,
    "memory_tip": "Barrier = rào cản ngăn cản.",
    "is_common": True,
    "stage": 3,
    "created_at": None,
    "updated_at": None
})

# 2. basis
records.append({
    "id": None,
    "english": "basis",
    "type": "noun",
    "vietnamese": "cơ sở; nền tảng",
    "pronounce": "/ˈbeɪsɪs/",
    "explain": "Nền tảng hoặc cơ sở quan trọng nhất để một điều gì đó phát triển hoặc tồn tại.",
    "example": "Trust is the basis of any successful business relationship.",
    "example_vietnamese": "Sự tin tưởng là cơ sở của bất kỳ mối quan hệ kinh doanh thành công nào.",
    "image_url": None,
    "audio_url": None,
    "difficulty": "medium",
    "cefr_level": "B1",
    "toeic_level": 500,
    "frequency": 55,
    "synonyms": ["foundation", "base", "groundwork", "cornerstone"],
    "antonyms": [],
    "word_family": ["basic", "basically"],
    "collocations": ["on a daily basis", "basis for", "regular basis", "basis of"],
    "phrasal_verbs": [],
    "grammar_pattern": "on + time + basis",
    "common_mistakes": None,
    "usage_note": "Thường dùng với cấu trúc 'on a ... basis'.",
    "topic": "General Business Operations",
    "mnemonic": None,
    "mnemonic_type": None,
    "memory_tip": "Basis = cơ sở nền tảng.",
    "is_common": True,
    "stage": 2,
    "created_at": None,
    "updated_at": None
})

# 3. be aware of
records.append({
    "id": None,
    "english": "be aware of",
    "type": "phrasal verb",
    "vietnamese": "biết; nhận thức được",
    "pronounce": "/biː əˈweə(r) ɒv/",
    "explain": "Có kiến thức hoặc nhận thức về cái gì đó.",
    "example": "Employees should be aware of company policies and procedures.",
    "example_vietnamese": "Nhân viên nên nhận thức được các chính sách và quy trình của công ty.",
    "image_url": None,
    "audio_url": None,
    "difficulty": "medium",
    "cefr_level": "B1",
    "toeic_level": 500,
    "frequency": 50,
    "synonyms": ["be conscious of", "be informed of", "be knowledgeable about"],
    "antonyms": ["be unaware of", "be ignorant of"],
    "word_family": [],
    "collocations": ["be aware of the risks", "be aware of the situation", "be fully aware of"],
    "phrasal_verbs": [],
    "grammar_pattern": "be aware of + N",
    "common_mistakes": None,
    "usage_note": "Trang trọng, dùng trong văn bản kinh doanh.",
    "topic": "General Business Operations",
    "mnemonic": None,
    "mnemonic_type": None,
    "memory_tip": "Be aware of = biết/nhận thức được.",
    "is_common": True,
    "stage": 2,
    "created_at": None,
    "updated_at": None
})

# 4. be in charge of
records.append({
    "id": None,
    "english": "be in charge of",
    "type": "phrasal verb",
    "vietnamese": "chịu trách nhiệm; phụ trách",
    "pronounce": "/biː ɪn tʃɑːdʒ ɒv/",
    "explain": "Có trách nhiệm hoặc quyền kiểm soát một cái gì đó.",
    "example": "She is in charge of the marketing department and reports directly to the CEO.",
    "example_vietnamese": "Cô ấy phụ trách bộ phận marketing và báo cáo trực tiếp cho CEO.",
    "image_url": None,
    "audio_url": None,
    "difficulty": "medium",
    "cefr_level": "B1",
    "toeic_level": 500,
    "frequency": 45,
    "synonyms": ["be responsible for", "manage", "supervise", "oversee"],
    "antonyms": ["be subordinate to", "report to"],
    "word_family": [],
    "collocations": ["be in charge of a project", "be in charge of operations", "be in charge of the team"],
    "phrasal_verbs": [],
    "grammar_pattern": "be in charge of + N",
    "common_mistakes": None,
    "usage_note": "Thường dùng để mô tả vai trò quản lý.",
    "topic": "Personnel & Human Resources",
    "mnemonic": None,
    "mnemonic_type": None,
    "memory_tip": "Be in charge of = chịu trách nhiệm/phụ trách.",
    "is_common": True,
    "stage": 2,
    "created_at": None,
    "updated_at": None
})

# 5. be made of
records.append({
    "id": None,
    "english": "be made of",
    "type": "phrasal verb",
    "vietnamese": "được làm từ; được chế tạo từ",
    "pronounce": "/biː meɪd ɒv/",
    "explain": "Được cấu tạo hoặc sản xuất từ một vật liệu nào đó.",
    "example": "The new product is made of sustainable materials and meets all environmental standards.",
    "example_vietnamese": "Sản phẩm mới được làm từ các vật liệu bền vững và đáp ứng tất cả các tiêu chuẩn môi trường.",
    "image_url": None,
    "audio_url": None,
    "difficulty": "easy",
    "cefr_level": "A2",
    "toeic_level": 400,
    "frequency": 60,
    "synonyms": ["be composed of", "be constructed from", "consist of"],
    "antonyms": [],
    "word_family": [],
    "collocations": ["be made of plastic", "be made of metal", "be made of wood"],
    "phrasal_verbs": [],
    "grammar_pattern": "be made of + material",
    "common_mistakes": "Thường nhầm lẫn với 'be made from' - 'made of' dùng cho vật liệu vẫn giữ dạng, 'made from' dùng cho vật liệu đã chuyển đổi.",
    "usage_note": "Dùng cho vật liệu vẫn giữ nguyên dạng sau khi chế tạo.",
    "topic": "Manufacturing & Production",
    "mnemonic": None,
    "mnemonic_type": None,
    "memory_tip": "Be made of = được làm từ (vật liệu giữ dạng).",
    "is_common": True,
    "stage": 1,
    "created_at": None,
    "updated_at": None
})

# 6. be ready for
records.append({
    "id": None,
    "english": "be ready for",
    "type": "phrasal verb",
    "vietnamese": "sẵn sàng cho; chuẩn bị cho",
    "pronounce": "/biː ˈredi fɔː(r)/",
    "explain": "Được chuẩn bị hoặc có thể thực hiện một việc gì đó.",
    "example": "The team is ready for the upcoming product launch and has completed all preparations.",
    "example_vietnamese": "Đội ngũ đã sẵn sàng cho việc ra mắt sản phẩm sắp tới và đã hoàn thành tất cả các công tác chuẩn bị.",
    "image_url": None,
    "audio_url": None,
    "difficulty": "easy",
    "cefr_level": "A2",
    "toeic_level": 400,
    "frequency": 55,
    "synonyms": ["be prepared for", "be set for", "be geared up for"],
    "antonyms": ["be unprepared for", "be not ready for"],
    "word_family": [],
    "collocations": ["be ready for action", "be ready for the meeting", "be ready for change"],
    "phrasal_verbs": [],
    "grammar_pattern": "be ready for + N/V-ing",
    "common_mistakes": None,
    "usage_note": "Thường dùng trong ngữ cảnh kinh doanh và dự án.",
    "topic": "General Business Operations",
    "mnemonic": None,
    "mnemonic_type": None,
    "memory_tip": "Be ready for = sẵn sàng cho.",
    "is_common": True,
    "stage": 1,
    "created_at": None,
    "updated_at": None
})

# 7. bear
records.append({
    "id": None,
    "english": "bear",
    "type": "verb",
    "vietnamese": "chịu đựng; mang theo",
    "pronounce": "/beə(r)/",
    "explain": "Chịu đựng khó khăn hoặc mang theo trách nhiệm.",
    "example": "The company must bear the cost of the recall.",
    "example_vietnamese": "Công ty phải chịu chi phí của việc thu hồi sản phẩm.",
    "image_url": None,
    "audio_url": None,
    "difficulty": "medium",
    "cefr_level": "B2",
    "toeic_level": 600,
    "frequency": 40,
    "synonyms": ["endure", "tolerate", "carry", "shoulder"],
    "antonyms": ["avoid", "reject", "refuse"],
    "word_family": ["bearable", "unbearable"],
    "collocations": ["bear the cost", "bear responsibility", "bear in mind"],
    "phrasal_verbs": ["bear with", "bear out"],
    "grammar_pattern": "bear + N",
    "common_mistakes": "Có thể nhầm lẫn với 'bare' (trần) - 'bear' có nghĩa là chịu đựng.",
    "usage_note": "Đa nghĩa, cần xem ngữ cảnh để hiểu đúng nghĩa.",
    "topic": "General Business Operations",
    "mnemonic": None,
    "mnemonic_type": None,
    "memory_tip": "Bear = chịu đựng (khác với bare = trần).",
    "is_common": True,
    "stage": 3,
    "created_at": None,
    "updated_at": None
})

# 8. beforehand
records.append({
    "id": None,
    "english": "beforehand",
    "type": "adverb",
    "vietnamese": "trước đó; trước lúc",
    "pronounce": "/bɪˈfɔːhænd/",
    "explain": "Trước một sự kiện hoặc thời điểm nhất định.",
    "example": "Please book the conference room beforehand.",
    "example_vietnamese": "Vui lòng đặt phòng họp trước đó.",
    "image_url": None,
    "audio_url": None,
    "difficulty": "medium",
    "cefr_level": "B1",
    "toeic_level": 500,
    "frequency": 45,
    "synonyms": ["in advance", "ahead of time", "previously"],
    "antonyms": ["afterwards", "later", "subsequently"],
    "word_family": [],
    "collocations": ["notify beforehand", "prepare beforehand", "arrange beforehand"],
    "phrasal_verbs": [],
    "grammar_pattern": "Common usage (adverb)",
    "common_mistakes": None,
    "usage_note": "Thường dùng để nhấn mạnh sự chuẩn bị trước.",
    "topic": "General Business Operations",
    "mnemonic": None,
    "mnemonic_type": None,
    "memory_tip": "Beforehand = trước đó/trước lúc.",
    "is_common": True,
    "stage": 2,
    "created_at": None,
    "updated_at": None
})

# 9. behaviour
records.append({
    "id": None,
    "english": "behaviour",
    "type": "noun",
    "vietnamese": "hành vi; thái độ",
    "pronounce": "/bɪˈheɪvjə(r)/",
    "explain": "Cách một người hoặc vật phản ứng hoặc hành động trong các tình huống khác nhau.",
    "example": "Professional behaviour is expected in the workplace.",
    "example_vietnamese": "Hành vi chuyên nghiệp được mong đợi trong môi trường làm việc.",
    "image_url": None,
    "audio_url": None,
    "difficulty": "medium",
    "cefr_level": "B1",
    "toeic_level": 500,
    "frequency": 50,
    "synonyms": ["conduct", "manners", "attitude", "deportment"],
    "antonyms": [],
    "word_family": ["behave", "behavioral"],
    "collocations": ["consumer behaviour", "professional behaviour", "organizational behaviour"],
    "phrasal_verbs": [],
    "grammar_pattern": "Common usage",
    "common_mistakes": "Có thể viết thành 'behavior' (American English) hoặc 'behaviour' (British English).",
    "usage_note": "Quan trọng trong nhân sự và quản lý.",
    "topic": "Personnel & Human Resources",
    "mnemonic": None,
    "mnemonic_type": None,
    "memory_tip": "Behaviour = hành vi/thái độ.",
    "is_common": True,
    "stage": 2,
    "created_at": None,
    "updated_at": None
})

# 10. benchmark
records.append({
    "id": None,
    "english": "benchmark",
    "type": "noun",
    "vietnamese": "tiêu chuẩn; mốc tham chiếu",
    "pronounce": "/ˈbentʃmɑːk/",
    "explain": "Tiêu chuẩn hoặc điểm tham chiếu dùng để so sánh và đánh giá hiệu suất.",
    "example": "This product sets a new benchmark for quality in the industry.",
    "example_vietnamese": "Sản phẩm này đặt ra một tiêu chuẩn mới về chất lượng trong ngành.",
    "image_url": None,
    "audio_url": None,
    "difficulty": "medium",
    "cefr_level": "B2",
    "toeic_level": 600,
    "frequency": 45,
    "synonyms": ["standard", "criterion", "yardstick", "reference point"],
    "antonyms": [],
    "word_family": [],
    "collocations": ["benchmark performance", "set a benchmark", "benchmark against"],
    "phrasal_verbs": [],
    "grammar_pattern": "Common usage",
    "common_mistakes": None,
    "usage_note": "Thường dùng trong quản lý và đánh giá hiệu suất.",
    "topic": "General Business Operations",
    "mnemonic": None,
    "mnemonic_type": None,
    "memory_tip": "Benchmark = tiêu chuẩn/mốc tham chiếu.",
    "is_common": True,
    "stage": 3,
    "created_at": None,
    "updated_at": None
})

# Save test records
with open(r'D:\CNTT2311\HK8\DOAN3\toeic-ai\test_10_words_model_knowledge.json', 'w', encoding='utf-8') as f:
    json.dump(records, f, ensure_ascii=False, indent=2)

print(f'Created {len(records)} test records using model knowledge')
print(f'Saved to test_10_words_model_knowledge.json')
print(f'\nWords processed:')
for word in test_words:
    print(f'  - {word}')
